version: "3.9"

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
      - ./endpoints.yml:/app/endpoints.yml
      - ./app/data:/app/data   # Rasa sẽ tạo tự động rasa.db
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --endpoints
      - /app/endpoints.yml
      - --debug
    networks:
      - rasa_network

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./actions:/app/actions
      - ./scripts:/app/scripts
      - ./chat_data:/app/chat_data
    ports:
      - "5055:5055"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - rasa_network

networks:
  rasa_network:
    driver: bridge
