<<<<<<< HEAD
version: "3.9"
=======
version: "3.0"
>>>>>>> parent of 7438095 (6/11)

services:
  rasa:
    image: rasa/rasa:3.6.20
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --endpoints
      - /app/endpoints.yml
    depends_on:
      - action_server
<<<<<<< HEAD
      - postgres
=======
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/rasa
>>>>>>> parent of 7438095 (6/11)
    networks:
      - rasa_network

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./actions:/app/actions
      - ./scripts:/app/scripts
    ports:
      - "5055:5055"
    depends_on:
<<<<<<< HEAD
      - postgres
=======
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/rasa
>>>>>>> parent of 7438095 (6/11)
    networks:
      - rasa_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: rasa_db
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - rasa_network

volumes:
  pg_data:

networks:
  rasa_network:
    driver: bridge
