services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
      - ./endpoints.yml:/app/endpoints.yml
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --endpoints
      - /app/endpoints.yml
      - --debug
    depends_on:
      - mongodb
      - action_server

    environment:
      - MONGO_URL=mongodb://mongodb:27017/rasa
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - rasa_network

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./actions:/app/actions
      - ./scripts:/app/scripts
      - ./chat_data:/app/chat_data
    ports:
      - "5055:5055"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/rasa
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - rasa_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - rasa_network

volumes:
  mongo_data:

networks:
  rasa_network:
    driver: bridge
