version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: rasa_mongo
    restart: always
    ports:
      - "27017:27017"
    # Không đặt username/password → MongoDB chạy chế độ không auth
    volumes:
      - mongo_data:/data/db
    networks:
      - rasa_network

  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./endpoints.yml:/app/endpoints.yml
      - ./app/data:/app/data  
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --endpoints
      - /app/endpoints.yml
      - --debug
    depends_on:
      - mongo
    networks:
      - rasa_network

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./actions:/app/actions
      - ./scripts:/app/scripts
      - ./chat_data:/app/chat_data
    ports:
      - "5055:5055"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - rasa_network

volumes:
  mongo_data:

networks:
  rasa_network:
    driver: bridge
